#!/usr/bin/env python3
"""
Reporting for the options-wheel paper bot.

Pulls live state from the Alpaca account (account, positions, option fills),
classifies each underlying's place in the wheel, computes net premium collected,
and writes a dated Markdown report into <project>/reports/.

Paths are derived from this script's location (repo-portable):
  SCRIPT_DIR = <repo>/deploy, REPO_DIR = <repo>, PROJECT_DIR = <repo>/..

Run with the repo venv (has requests + python-dotenv):
  <repo>/.venv/bin/python deploy/wheel_report.py
"""
import os
import sys
import datetime as dt
from pathlib import Path

import requests
from dotenv import load_dotenv

# On Windows this box's default codec is cp950 (HK locale); the report contains
# Unicode glyphs. Make stdout tolerant so a redirected print() never crashes.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_DIR = SCRIPT_DIR.parent
PROJECT_DIR = REPO_DIR.parent
REPORTS_DIR = PROJECT_DIR / "reports"
ENV_FILE = REPO_DIR / ".env"
START_EQUITY = 100_000.0  # paper account starting balance

load_dotenv(ENV_FILE)
KEY = os.environ.get("ALPACA_API_KEY")
SECRET = os.environ.get("ALPACA_SECRET_KEY")
IS_PAPER = os.environ.get("IS_PAPER", "true").lower() == "true"
BASE = "https://paper-api.alpaca.markets" if IS_PAPER else "https://api.alpaca.markets"
HEADERS = {"APCA-API-KEY-ID": KEY or "", "APCA-API-SECRET-KEY": SECRET or ""}


def api(path, params=None):
    r = requests.get(f"{BASE}{path}", headers=HEADERS, params=params, timeout=30)
    r.raise_for_status()
    return r.json()


def parse_occ(sym):
    """OCC option symbol -> (underlying, expiry date, 'C'/'P', strike float). None if not an option."""
    if len(sym) < 16 or not sym[-15:-9].isdigit():
        return None
    body = sym[-15:]
    underlying = sym[: -15]
    yy, mm, dd = int(body[0:2]), int(body[2:4]), int(body[4:6])
    expiry = dt.date(2000 + yy, mm, dd)
    opt_type = body[6]
    strike = int(body[7:]) / 1000.0
    return underlying, expiry, opt_type, strike


def money(x):
    return f"${float(x):,.2f}"


def main():
    if not KEY or not SECRET:
        sys.exit("ERROR: ALPACA_API_KEY / ALPACA_SECRET_KEY not loaded from .env")

    acct = api("/v2/account")
    positions = api("/v2/positions")
    # all option sell/buy fills for net premium
    orders = api("/v2/orders", {"status": "all", "limit": 500, "nested": "false"})

    now = dt.datetime.now().astimezone()
    equity = float(acct["equity"])
    total_pl = equity - START_EQUITY

    # --- classify wheel state per underlying & sum open unrealized P/L ---
    rows = []          # per-position display rows
    state = {}         # underlying -> wheel stage
    open_upl = 0.0
    for p in positions:
        upl = float(p.get("unrealized_pl", 0) or 0)
        open_upl += upl
        occ = parse_occ(p["symbol"])
        qty = int(p["qty"])
        if occ:
            und, exp, typ, strike = occ
            kind = f"short {'put' if typ=='P' else 'call'}"
            detail = f"{und} {strike:g}{typ} exp {exp}"
            stage = "short_put" if typ == "P" else "short_call"
            state.setdefault(und, stage)
            rows.append((und, kind, detail, qty, money(p["market_value"]), money(upl)))
        else:
            und = p["symbol"]
            state.setdefault(und, "long_shares (assigned)")
            rows.append((und, "long shares", f"{qty} sh @ {money(p['avg_entry_price'])}",
                         qty, money(p["market_value"]), money(upl)))

    # --- net premium from option fills (sells collect, buys-to-close pay) ---
    prem_collected = prem_paid = 0.0
    fills = []
    for o in orders:
        if o.get("filled_qty") in (None, "0") or not o.get("filled_avg_price"):
            continue
        occ = parse_occ(o["symbol"])
        if not occ:
            continue
        cash = float(o["filled_avg_price"]) * 100 * int(o["filled_qty"])
        if o["side"] == "sell":
            prem_collected += cash
        else:
            prem_paid += cash
        fills.append((o.get("filled_at") or o.get("submitted_at"), o["symbol"],
                      o["side"], o["filled_qty"], o["filled_avg_price"]))
    net_prem = prem_collected - prem_paid
    fills.sort(reverse=True)

    # --- render markdown ---
    L = []
    L.append(f"# Wheel Report — {now:%Y-%m-%d %H:%M %Z}")
    L.append("")
    L.append(f"*Account: {'PAPER' if IS_PAPER else 'LIVE'} · generated by `wheel_report.py`*")
    L.append("")
    L.append("## Account")
    L.append(f"- Equity: **{money(equity)}**  (start {money(START_EQUITY)} → **PnL {money(total_pl)}**)")
    L.append(f"- Cash: {money(acct['cash'])}  ·  Buying power: {money(acct['buying_power'])}")
    L.append(f"- Open positions unrealized P/L: {money(open_upl)}")
    L.append(f"- Net option premium (lifetime fills): **{money(net_prem)}**  "
             f"(collected {money(prem_collected)} − bought-back {money(prem_paid)})")
    L.append("")
    L.append("## Wheel state")
    if state:
        L.append("| Symbol | Stage |")
        L.append("|---|---|")
        for und in sorted(state):
            L.append(f"| {und} | {state[und]} |")
    else:
        L.append("_No open positions — wheel idle (will sell puts on next run)._")
    L.append("")
    L.append("## Open positions")
    if rows:
        L.append("| Underlying | Type | Detail | Qty | Mkt value | Unreal. P/L |")
        L.append("|---|---|---|---:|---:|---:|")
        for r in sorted(rows):
            L.append(f"| {r[0]} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |")
    else:
        L.append("_None._")
    L.append("")
    L.append("## Recent option fills (last 10)")
    if fills:
        L.append("| When | Symbol | Side | Qty | Price |")
        L.append("|---|---|---|---:|---:|")
        for f in fills[:10]:
            when = (f[0] or "")[:19].replace("T", " ")
            L.append(f"| {when} | {f[1]} | {f[2]} | {f[3]} | ${f[4]} |")
    else:
        L.append("_No option fills yet._")
    L.append("")
    report = "\n".join(L) + "\n"

    REPORTS_DIR.mkdir(exist_ok=True)
    out = REPORTS_DIR / f"wheel_report_{now:%Y-%m-%d}.md"
    out.write_text(report, encoding="utf-8")
    print(report)
    print(f"\n[written to {out}]")


if __name__ == "__main__":
    main()
